Repository kikuyodev/kumi-server, pull requests merged in 2023-12, with the labels that each got.

#1 Add remaining finishing touches to the server
  Kumi.Server/WebSockets/Hubs/Identification/AuthenticationHub.cs
Labels: size: xs

#2 Hotfixes to Client -> Server communication
  Kumi.Server/Server.cs
  Kumi.Server/WebSockets/Hubs/Meta/PingHub.cs
  Kumi.Server/WebSockets/WebsocketServer.cs
Labels: size: l

#3 Create chat channel infrastructure
  Kumi.Server/Database/DatabaseContext.cs
  Kumi.Server/Database/Models/ChatChannel.cs
  Kumi.Server/IO/ConnectionList.cs
  Kumi.Server/IO/IConnectionEnumerable.cs
  Kumi.Server/Processing/QueueItem.cs
  Kumi.Server/Processing/QueueProcessor.cs
  Kumi.Server/Queues/ChatEvent.cs
  Kumi.Server/Queues/ChatQueue.cs
  Kumi.Server/WebSockets/Connection.cs
  Kumi.Server/WebSockets/Hubs/Identification/AuthenticationHub.cs
  Kumi.Server/WebSockets/WebsocketServer.cs
Labels: size: l

#4 Fix chat message handling
  Kumi.Server/Queues/ChatQueue.cs
  Kumi.Server/WebSockets/Connection.cs
  Kumi.Server/WebSockets/WebsocketServer.cs
Labels: size: s
